---
- name: Include vars
  include_vars: ../vars/ah_ee_repositories.yml
  tags:
    - repos

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.ee_repository
  tags:
    - repos
...
