---
- name: Include vars
  include_vars: ../vars/ah_groups.yml
  tags:
    - groups

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.group
  tags:
    - groups
...
