---
- name: Include vars
  include_vars: ../vars/ah_ee_registries.yml
  tags:
    - registries

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.ee_registry
  tags:
    - registries
...
